export { PrismaClient } from '@prisma/client';
export { prisma } from './client';
export type {
  Student,
  Vendor,
  Admin,
  FoodStall,
  MenuCategory,
  MenuItem,
  Inventory,
  Order,
  OrderItem,
  OrderStatusHistory,
  PickupSlot,
  Payment,
  Invoice,
  WalletTransaction,
  Review,
  FavoriteFood,
  Notification,
  Conversation,
  ChatMessage,
  Recommendation,
  QueueStatus,
  Analytics,
  DemandPrediction,
  KnowledgeBase,
  Announcement,
  FAQ,
  SupportTicket,
  SupportTicketReply,
  AuditLog,
  SystemConfig,
  Coupon,
  MenuItemEmbedding,
  StudentSession,
  VendorSession,
  AdminSession,
  PasswordReset,
  Prisma,
} from '@prisma/client';

export {
  UserRole,
  StudentStatus,
  VendorStatus,
  StallStatus,
  StallCategory,
  DietaryType,
  MenuItemStatus,
  MealCategory,
  OrderStatus,
  PaymentStatus,
  PaymentMethod,
  NotificationType,
  NotificationChannel,
  PickupSlotStatus,
  ConversationStatus,
  MessageRole,
  MessageType,
  PredictionType,
  TicketStatus,
  TicketPriority,
  AnnouncementTarget,
  AnnouncementStatus,
  ReviewStatus,
  TransactionType,
  AuditAction,
  EmbeddingType,
} from '@prisma/client';
